---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
  - name: starting leela java docker
    docker_container:
      name: leela-java
      image: openjdk
      state: started
      recreate: yes
      pull: yes
      restart: yes
      restart_policy: unless-stopped
      ports:
         - "555"




